from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGridLayout, QComboBox
from CamList import camScan


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        width = QtWidgets.QApplication.desktop().width()
        height = QtWidgets.QApplication.desktop().height()
        self.k_width = width / 1920
        kW = self.k_width
        self.k_height = height / 1080
        kH = self.k_height

        MainWindow.resize(1920 * kW, 1080 * kH)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(int(10 * kW), int(10 * kH), int(660 * kW),int(480 * kH)))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(int(10 * kW), int(500 * kH), int(660 * kW), int(480 * kH)))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(int(1600 * kW), int(630 * kH), int(230 * kW), int(40 * kH)))
        self.pushButton_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(int(1600 * kW), int(70 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(int(1600 * kW), int(110 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(int(1600 * kW), int(30 * kH), int(230 * kW), int(30 * kH)))
        self.label_3.setStyleSheet("background-color: rgb(153, 255, 153);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(int(1600 * kW), int(210 * kH), int(230 * kW), int(30 * kH)))
        self.label_4.setStyleSheet("background-color: rgb(153, 255, 153);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(int(1600 * kW), int(150 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(int(1600 * kW), int(250 * kH), int(231 * kW), int(31 * kH)))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(int(1600 * kW), int(290 * kH), int(230 * kW), int(30 * kH)))
        self.label_5.setStyleSheet("background-color: rgb(153, 255, 153);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(int(1600 * kW), int(330 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(int(1600 * kW), int(370 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(int(1460 * kW), int(70 * kH), int(130 * kW), int(30 * kH)))
        self.label_6.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(int(1460 * kW), int(110 * kH), int(130 * kW), int(30 * kH)))
        self.label_7.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(int(1460 * kW), int(150 * kH), int(130 * kW), int(30 * kH)))
        self.label_8.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(int(1460 * kW), int(250 * kH), int(130 * kW), int(30 * kH)))
        self.label_9.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(int(1460 * kW), int(330 * kH), int(130 * kW), int(30 * kH)))
        self.label_11.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(int(1460 * kW), int(370 * kH), int(130 * kW), int(30 * kH)))
        self.label_12.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.label_12.setObjectName("label_12")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(int(1640 * kW), int(730 * kH), int(220 * kW), int(50 * kH)))
        self.pushButton_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(int(1390 * kW), int(10 * kH), int(470 * kW), int(20 * kH)))
        self.line.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(int(1390 * kW), int(700 * kH), int(470 * kW), int(20 * kH)))
        self.line_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(int(1380 * kW), int(20 * kH), int(20 * kW), int(690 * kH)))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(int(1850 * kW), int(20 * kH), int(20 * kW), int(690 * kH)))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(int(1460 * kW), int(30 * kH), int(230 * kW), int(30 * kH)))
        self.radioButton.setObjectName("radioButton")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(int(1460 * kW), int(425 * kH), int(130 * kW), int(30 * kH)))
        self.label_16.setObjectName("label_16")
        self.label_16.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(int(1700 * kW), int(425 * kH), int(130 *kW), int(30 * kH)))
        self.label_13.setObjectName("label_13")
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.label_14.setGeometry(QtCore.QRect(int(1700 * kW), int(465 * kH), int(130 * kW), int(30 * kH)))
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setGeometry(QtCore.QRect(int(1600 * kW), int(465 * kH), int(60 * kW), int(30 * kH)))
        self.lineEdit_7.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.label_15.setGeometry(QtCore.QRect(int(1460 * kW), int(465 * kH), int(130 * kW), int(30 * kH)))
        self.label_15.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName("lineEdit_7")
        self.lineEdit_8.setGeometry(QtCore.QRect(int(1600 * kW), int(425 * kH), int(60 * kW), int(30 * kH)))
        self.lineEdit_8.setStyleSheet("background-color: rgb(255, 255, 255)")

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(int(1390 * kW), int(730 * kH), int(220 * kW), int(50 * kH)))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(int(1460 * kW), int(630 * kH), int(130 * kW), int(40 * kH)))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(int(685 * kW), int(500 * kH), int(660 * kW), int(480* kH)))
        self.label_10.setObjectName("label_10")
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, int(1640 * kW), int(26 * kH)))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(int(1515 * kW), int(790 * kH), int(220 * kW), int(50 * kH)))
        self.pushButton_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(int(900 * kW), int(10 * kH), int(450 * kW), int(60 * kH)))
        self.label_17.setObjectName("label_17")
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
                                        "font: 10pt \"MS Shell Dlg 2\";")

        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(int(1460*kW), int(550*kH), int(130*kW), int(30*kH)))
        self.label_18.setObjectName("label_18")
        self.label_18.setStyleSheet("background-color: rgb(221, 221, 221);")

        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(int(1600*kW), int(550*kH), int(230*kW), int(30*kH)))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setStyleSheet("background-color: rgb(255, 255, 255)")

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(int(1460*kW), int(510*kH), int(130*kW), int(30*kH)))
        self.label_19.setObjectName("label_19")
        self.label_19.setStyleSheet("background-color: rgb(221, 221, 221);")

        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(int(1600 * kW), int(510 * kH), int(230 * kW), int(30 * kH)))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setStyleSheet("background-color: rgb(255, 255, 255);")


        self.combo = QComboBox(self.centralwidget)
        self.combo.setGeometry(QtCore.QRect(int(1600*kW), int(590*kH), int(230 * kW), int(30 * kH)))
        cams = camScan()
        i = 0
        while i < len(cams):
            self.combo.addItem(str(cams[i]))
            i += 1


        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(self.label.clear)
        self.pushButton_2.clicked.connect(self.label_2.clear)
        self.pushButton_2.clicked.connect(self.label_10.clear)
        self.pushButton_2.clicked.connect(self.label_17.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", "Применить параметры"))
        self.label_3.setText(_translate("MainWindow", "Параметры канала G:"))
        self.label_4.setText(_translate("MainWindow", "Сканирование:"))
        self.label_5.setText(_translate("MainWindow", "Вариация выборки:"))
        self.label_6.setText(_translate("MainWindow", "К-т G для пламени:"))
        self.label_7.setText(_translate("MainWindow", "К-т G для дыма:"))
        self.label_8.setText(_translate("MainWindow", "Размер Ядра Гаусса:"))
        self.label_9.setText(_translate("MainWindow", "Размер окна:"))
        self.label_10.setText(_translate("MainWindow", ""))
        self.label_11.setText(_translate("MainWindow", "Количество кадров: "))
        self.label_12.setText(_translate("MainWindow", "Период, сек. :"))
        self.label_13.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", ""))
        self.label_15.setText(_translate("MainWindow", "ЗИ для дыма, %: "))
        self.pushButton_3.setText(_translate("MainWindow", "Стоп"))
        self.radioButton.setText(_translate("MainWindow", "Видео"))
        self.label_16.setText(_translate("MainWindow", "ЗИ для огня, %: "))
        self.pushButton_5.setText(_translate("MainWindow", "Старт"))
        self.pushButton_6.setText(_translate("MainWindow", "Анализ"))
        self.pushButton_7.setText(_translate("MainWindow", "Путь"))
        self.label_18.setText(_translate("MainWindow", "Время обновления, сек. : "))
        self.label_19.setText(_translate("MainWindow", "К-т бинаризации: "))

        self.lineEdit.setText(_translate("MainWindow", "0.54"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.32"))
        self.lineEdit_3.setText(_translate("MainWindow", "5"))
        self.lineEdit_4.setText(_translate("MainWindow", "12"))
        self.lineEdit_5.setText(_translate("MainWindow", "15"))
        self.lineEdit_6.setText(_translate("MainWindow", "---"))
        self.lineEdit_7.setText(_translate("MainWindow", "20"))
        self.lineEdit_8.setText(_translate("MainWindow", "20"))
        self.lineEdit_9.setText(_translate("MainWindow", "300"))
        self.lineEdit_10.setText(_translate("MainWindow", "1"))

