# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SetParams.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 289)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(230, 90, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 90, 211, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 31))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(221, 221, 221);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 211, 31))
        self.label_2.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 190, 211, 31))
        self.label_3.setStyleSheet("background-color: rgb(221, 221, 221);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 190, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 140, 181, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 401, 51))
        self.label_4.setStyleSheet("background-color: rgb(153, 255, 153);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(260, 230, 151, 41))
        self.pushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 230, 111, 41))
        self.pushButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "5"))
        self.label.setText(_translate("Dialog", "Размер ядра Гаусса G:"))
        self.label_2.setText(_translate("Dialog", "Размер окна сканирования:"))
        self.label_3.setText(_translate("Dialog", "Выборка:"))
        self.lineEdit_2.setText(_translate("Dialog", "15"))
        self.lineEdit_3.setText(_translate("Dialog", "20"))
        self.label_4.setText(_translate("Dialog", "Применяемые параметры"))
        self.pushButton.setText(_translate("Dialog", "Применить"))
        self.pushButton_2.setText(_translate("Dialog", "Сброс"))

class mywindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.initUI()

    # Настрока для виджетов в GUI
    def initUI(self):

        self.title = 'FireSmoke'
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    application = mywindow()
    application.show()
    sys.exit(app.exec())
